const D=['Prayer','Scripture','Solitude','Fasting','Sabbath','Community','Generosity','Witness','Service','Environment','Use of Time','Sleep','Physical Health','Inner Life'];
const MAP={busyness:['Use of Time','Sabbath','Solitude'],digital:['Environment','Solitude','Use of Time'],tiredness:['Sleep','Physical Health','Sabbath'],work:['Use of Time','Sabbath'],stress:['Inner Life','Solitude','Community'],dryness:['Prayer','Scripture','Inner Life'],uncertain:['Community','Scripture','Prayer'],overdoing:['Use of Time','Sabbath','Service'],relationships:['Community','Inner Life'],money:['Generosity'],witness:['Witness'],service:['Service','Sabbath'],emotional:['Inner Life','Community'],body:['Physical Health','Sleep'],dutiful:['Prayer','Scripture','Solitude','Fasting']};
function clamp(x){return Math.max(0,Math.min(1,x))}
function median(a){let x=a.filter(v=>typeof v==='number'&&!Number.isNaN(v)).sort((a,b)=>a-b);if(!x.length)return null;let m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function avg(a){let x=a.filter(v=>typeof v==='number'&&!Number.isNaN(v));return x.length?x.reduce((s,v)=>s+v,0)/x.length:null}
function deepPattern(c,i){if(c==null||i==null)return'Insufficient';if(c<2.7&&i<2.7)return'Begin';if(c<2.9&&i>=3.25)return'Make Room';if(c>=3.25&&i<2.9)return'Deepen';if(c>=3.65&&i>=3.65)return'Anchor';return'Hold Lightly'}
function quickPattern(m){if(m==null)return'Insufficient';if(m<2.65)return'Begin';if(m>=3.75)return'Anchor';return'Hold Lightly'}
function opportunityQuick(m,baseline){if(m==null)return 0;let relative=baseline==null?0:clamp((baseline-m+.10)/1.7);let absolute=clamp((3.0-m)/2.0);return clamp(.72*absolute+.28*relative)}
function opportunityDeep(c,i,p,baseline){if(c==null||i==null)return 0;let m=(c+i)/2,relative=baseline==null?0:clamp((baseline-m+.10)/1.8);if(p==='Begin')return clamp(.60*clamp((2.95-m)/1.95)+.40*relative);if(p==='Make Room'){let contrast=clamp((i-c-.10)/2.0);return clamp(.43*clamp((3.0-c)/2.0)+.42*contrast+.15*relative)}if(p==='Deepen'){let contrast=clamp((c-i-.10)/2.0);return clamp(.43*clamp((3.0-i)/2.0)+.42*contrast+.15*relative)}if(p==='Hold Lightly'&&baseline!=null&&m<baseline-.45)return clamp(.72*relative+.28*clamp((3.2-m)/2.2));return 0}
function interpret(profile){let mode=profile.mode==='deep'?'deep':'quick',rows={},means=[],coverages=[];D.forEach(d=>{let z=profile.data[d]||{},c=z.core,i=z.impact,nc=z.nCore==null?(c==null?0:4):z.nCore,ni=z.nImpact==null?(i==null?0:4):z.nImpact,cov=mode==='deep'?Math.min(nc/4,ni/4):nc/4;cov=clamp(cov);let m=c==null?null:(mode==='deep'&&i!=null?(c+i)/2:c);if(m!=null){means.push(m);coverages.push(cov)}let p=mode==='deep'?deepPattern(c,i):quickPattern(m);rows[d]={core:c,impact:i,mean:m,pattern:p,context:0,connection:false,coverage:cov}});let baseline=median(means),overall=avg(means),responseCoverage=avg(coverages)||0;(profile.barriers||[]).forEach(b=>(MAP[b]||[]).forEach((d,j)=>{if(rows[d])rows[d].context+=1-j*.18}));(profile.connections||[]).forEach(d=>{if(rows[d])rows[d].connection=true});D.forEach(d=>{let r=rows[d],base=mode==='deep'?opportunityDeep(r.core,r.impact,r.pattern,baseline):opportunityQuick(r.mean,baseline);r.opportunity=base*(.92+.08*r.coverage);r.final=r.opportunity;r.contextResonance=clamp(r.context/2.2)});
let raw=D.filter(d=>rows[d].mean!=null&&rows[d].opportunity>=.10).sort((a,b)=>rows[b].opportunity-rows[a].opportunity),candidates=[...raw];if(candidates.length>1){let top=rows[candidates[0]],second=rows[candidates[1]],gap=top.opportunity-second.opportunity;if(gap<.075){let tied=candidates.filter(d=>top.opportunity-rows[d].opportunity<.075);tied.sort((a,b)=>rows[b].contextResonance-rows[a].contextResonance||rows[b].opportunity-rows[a].opportunity);let best=tied[0],next=tied[1];if(next&&rows[best].contextResonance-rows[next].contextResonance>=.28)candidates=[best,...candidates.filter(x=>x!==best)]}}
let broad=overall!=null&&overall<2.35&&baseline<2.40&&means.length>=10,attention=null,confidence=broad?'Broad Invitation':'Open Invitation',alternates=[];if(!broad&&candidates.length){let a=rows[candidates[0]],b=candidates[1]?rows[candidates[1]]:null,gap=b?a.opportunity-b.opportunity:a.opportunity,reliable=a.coverage>=.75&&responseCoverage>=.80;if(reliable&&a.opportunity>=.50&&(!b||gap>=.14)){attention=candidates[0];confidence='Clear Attention';alternates=candidates.slice(1,3)}else if(reliable&&a.opportunity>=.34&&(!b||gap>=.075)){attention=candidates[0];confidence='Emerging Attention';alternates=candidates.slice(1,3)}else alternates=candidates.slice(0,3)}else if(broad)alternates=D.filter(d=>rows[d].mean!=null).sort((a,b)=>rows[a].mean-rows[b].mean).slice(0,3);
let anchorPool=D.filter(d=>{let r=rows[d];if(r.mean==null||r.coverage<.75)return false;let absolute=mode==='deep'?(r.core>=3.60&&r.impact>=3.60):r.mean>=3.75,relative=baseline!=null&&r.mean>=baseline+.30,exceptional=r.mean>=4.40;return absolute&&(relative||exceptional)}).sort((a,b)=>rows[b].mean-rows[a].mean),anchors=[];if(anchorPool.length){let top=rows[anchorPool[0]].mean,second=anchorPool[1]?rows[anchorPool[1]].mean:null;if(second!=null&&Math.abs(top-second)<.10){let tied=anchorPool.filter(d=>top-rows[d].mean<.10);if(tied.length<=2)anchors=tied}else anchors=[anchorPool[0]]}
return{rows,candidates,attention,confidence,alternates,anchors,broad,diagnostic:{mode,baseline,overall,responseCoverage,completeness:means.length/D.length,attentionGap:candidates[1]?rows[candidates[0]].opportunity-rows[candidates[1]].opportunity:(candidates[0]?rows[candidates[0]].opportunity:0),version:'2.2',stressTest:'validated'}}}
window.FormationEngine={D,MAP,deepPattern,quickPattern,opportunityQuick,opportunityDeep,interpret};