(()=>{const chapters={Body:'First, your body. How is it carrying this season?',Inner:'And how are you underneath everything?',Rest:'Now consider rest and enjoyment — the parts of life that do not need to achieve anything.',Relationships:'Think about the people closest to you.',Work:'Now your work, responsibilities and sense of purpose.',Faith:'Finally, notice your life with God — without judging it.'};
const Q=[['Body','Sleep','How is your sleep at the moment?'],['Body','Energy','How much usable energy do you have for ordinary life?'],['Body','Nourishment','How well is the way you eat and drink supporting you?'],['Body','Movement','How life-giving is movement or exercise at the moment?'],['Inner','Inner space','How much inner space do you have to notice what you are feeling?'],['Inner','Joy','How much interest, enjoyment or delight are you experiencing?'],['Inner','Stress','How manageable does your stress or mental load feel?'],['Rest','Rest','How much genuine stopping and rest is there in your week?'],['Rest','Recreation','How much room is there for play, hobbies, nature or things you enjoy?'],['Relationships','Close relationship','How connected and supported do you feel in your closest adult relationships?'],['Relationships','Family','How able are you to be meaningfully present to family or those you care for?'],['Relationships','Friendship','How known and supported do you feel in friendship?'],['Work','Workload','How sustainable do your work and responsibilities feel?'],['Work','Purpose','How much meaning or purpose do you sense in how you spend your time?'],['Faith','God','How connected to God do you feel in this season?'],['Faith','Receptivity','How much room is there to receive from God rather than only doing things for God?'],['Faith','Community','How supported do you feel by Christian community or companions?']];
const S={
Sleep:['Very poor','Poor','Okay','Good','Restorative'],
Energy:['Running on empty','Low','Enough to get by','Good','Plenty'],
Nourishment:['Quite disrupted','Inconsistent','Mostly okay','Generally supportive','Consistently nourishing'],
Movement:['Almost none','Occasional','Fairly regular','Regular & helpful','A strong life-giving rhythm'],
'Inner space':['None — just pushing through','Very little','Some','Good space to notice','Spacious & attentive'],
Joy:['Almost none','Occasionally','Some','Often','A lot'],
Stress:['Overwhelming','Heavy','Manageable','Light','Very manageable'],
Rest:['None','Very little','Some','Regularly','Plenty'],
Recreation:['No room','Very little','Some','Regular room','A life-giving part of life'],
'Close relationship':['Deeply strained','Disconnected','Okay','Connected','Deeply connected'],
Family:['Rarely present','Often stretched','Somewhat present','Present','Deeply present'],
Friendship:['Alone','Thinly supported','Some support','Supported','Deeply supported'],
Workload:['Unsustainable','Draining','Manageable','Sustainable','Life-giving'],
Purpose:['Mostly empty','Lacking meaning','Mixed','Meaningful','Deeply purposeful'],
God:['Distant','Faintly connected','Uncertain / mixed','Connected','Deeply connected'],
Receptivity:['No room','Very little room','Some room','Regular space','Spacious'],
Community:['Disconnected','Thinly connected','Some connection','Supported','Deeply supported']
};const contexts=['New baby / young children','Work pressure','Relationship strain','Grief or loss','Health concerns','Caring responsibilities','Major transition','Study pressure','Financial pressure','Loneliness','A particularly good season','Life just feels full','Nothing obvious','Something else'];const needs=['Rest','Clarity','Connection','Courage','Joy','Peace','Purpose','Help','I’m not sure'];let i=0,A=[],ctx=new Set(),need='';
const $=x=>document.getElementById(x),avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function assessmentTop(){scrollTo(0,0);requestAnimationFrame(()=>scrollTo(0,0))}
function show(){const q=Q[i];$('chapterEy').textContent=q[0]==='Inner'?'Inner life':q[0];$('chapterIntro').textContent=chapters[q[0]];$('question').textContent=q[2];$('count').textContent=(i+1)+' of '+Q.length;$('bar').style.width=((i+1)/Q.length*100)+'%';$('scale').innerHTML=S[q[1]].map((x,n)=>'<button data-value="'+(n+1)+'" onclick="answer('+(n+1)+')">'+x+'</button>').join('');assessmentTop()}
window.start=()=>{$('intro').classList.add('hide');$('assess').classList.remove('hide');show()};window.answer=v=>{A[i]=v;if(document.activeElement instanceof HTMLElement)document.activeElement.blur();if(i<Q.length-1){i++;show()}else openSeason()};window.back=()=>{if(i){i--;show()}else{$('assess').classList.add('hide');$('intro').classList.remove('hide')}};function openSeason(){$('assess').classList.add('hide');$('season').classList.remove('hide');$('contexts').innerHTML=contexts.map(x=>'<button class="choice '+(ctx.has(x)?'on':'')+'" onclick="toggleContext(this)">'+x+'</button>').join('');$('needs').innerHTML=needs.map(x=>'<button class="'+(need===x?'on':'')+'" onclick="setNeed(this)">'+x+'</button>').join('');scrollTo(0,0)}window.toggleContext=b=>{ctx.has(b.textContent)?ctx.delete(b.textContent):ctx.add(b.textContent);b.classList.toggle('on')};window.setNeed=b=>{need=b.textContent;[...$('needs').children].forEach(x=>x.classList.toggle('on',x===b))};window.returnPulse=()=>{$('season').classList.add('hide');$('assess').classList.remove('hide');show()};
function analyse(){const key=Object.fromEntries(Q.map((q,n)=>[q[1],A[n]])),groups={};Q.forEach((q,n)=>(groups[q[0]]??=[]).push(A[n]));const scores=Object.entries(groups).map(([name,a])=>({name:name==='Inner'?'Inner life':name,v:avg(a)})),low=scores.slice().sort((a,b)=>a.v-b.v)[0],high=scores.slice().sort((a,b)=>b.v-a.v)[0],overall=avg(A);const exhaustion=avg([key.Sleep,key.Energy,key.Rest,key.Stress,key.Workload]);let b='ABIDE';if(exhaustion<2.7)b='RESTORE';else if(avg([key.God,key.Receptivity,key.Community])<2.6)b='RECONNECT';else if(key.Workload<3||key.Stress<3||key.Rest<3)b='REORDER';else if(overall<3.4)b='RENEW';const newBaby=ctx.has('New baby / young children'),work=ctx.has('Work pressure'),grief=ctx.has('Grief or loss'),good=ctx.has('A particularly good season');if(good&&overall>=3.5)b='ABIDE';return{key,scores,low,high,b,newBaby,work,grief}}
window.finish=()=>{const r=analyse(),note=$('godNote').value.trim();let title='Life feels fairly steady, with one place asking for care.',story='There is some strength in '+r.high.name.toLowerCase()+'. '+r.low.name+' feels thinner, but it does not need to become a problem to solve.';if(r.b==='RESTORE'){title='You may be carrying more than your body can comfortably hold.';story='Sleep, energy, rest or load are running thin. '+(r.newBaby?'With young children or a new baby in the picture, some tiredness belongs to the season rather than representing a failure of rhythm. ':'')+(r.work?'Work pressure also appears to be taking significant space. ':'')+'Tiredness can colour motivation, joy and even our awareness of God.'}else if(r.b==='RECONNECT'){title='Life is moving, but connection feels thinner.';story='Your responses suggest that connection with God or Christian companions may be harder to access right now. That is an invitation to relationship, not evidence that you are failing spiritually.'}else if(r.b==='REORDER'){title='There is life here, but not quite enough room.';story='Pressure, pace or limited rest appear to be crowding some of the things that help you remain present. The invitation may be subtraction before addition.'}else if(r.b==='ABIDE'){title='There is a lot of life here.';story='Several parts of life appear steady or life-giving. You do not need LIFEMAP to manufacture a weakness. This may be a season to receive what is good, give thanks and remain present to God within it.'}else{title='Several parts of life could use a little renewal.';story='Nothing needs to be dramatically wrong for life to become thin. Rather than improving everything, begin with one gentle source of life.'}if(r.grief)story+=' Grief is also part of this season; some heaviness may need companionship and space rather than correction.';if(note)story+=' You named something directly to God in this season; let that honesty remain part of the way forward.';$('storyTitle').textContent=title;$('story').textContent=story;renderBearing(r);$('map').innerHTML=r.scores.map(s=>'<div class="life"><div class="ey">'+s.name+'</div><b>'+(s.v>=4?'Life-giving':s.v>=3?'Steady':s.v>=2?'Stretched':'Depleted')+'</b></div>').join('');$('season').classList.add('hide');$('result').classList.remove('hide');scrollTo(0,0)};
function renderBearing(r){const data={RESTORE:['Let tiredness be something God meets, not something you have to overcome before meeting God.',['Life','Protect one realistic pocket of recovery this week — perhaps an earlier bedtime, a quieter evening, or one thing you will not carry.'],['With God','When you lie down, pray simply: “Jesus, I give you what I could not finish today.”'],['If it would help','Use a short guided night prayer such as Lectio 365 when finding your own words feels like work.']],RECONNECT:['Make a small place for relationship, not more religious output.',['With God','Give God five unhurried minutes of honesty. No agenda: simply name what this season actually feels like.'],['With others','Choose one safe person and let yourself be known a little more truthfully this week.'],['Remember','Connection often returns through presence before it returns through feeling.']],REORDER:['Create room before asking yourself for more effort.',['Life','Name one recurring source of hurry you can reduce, delegate, delay or leave undone.'],['With God','Let some of the recovered space become a walk, silence, prayer or simply being present with God.'],['Notice','Pay attention to what becomes available when everything is not crowded.']],RENEW:['Choose one gentle source of life rather than fixing the whole map.',['Life','Begin with '+r.low.name.toLowerCase()+'. What would make this area just a little more spacious or alive?'],['With God','Ask: “God, where are you already present here, and how can I receive your care?”'],['Keep it small','Choose something you can receive and repeat without turning it into another burden.']],ABIDE:['Don’t manufacture a problem. Receive the good that is already here.',['Notice','Once this week, stop in the middle of something good instead of rushing past it.'],['With God','Pray: “Thank you, God. Help me receive this and remain with you in it.”'],['Overflow','If it feels natural, let some of the life you are receiving become generosity, hospitality or encouragement for someone else.']]};const meanings={RESTORE:'Make room for recovery before asking more of yourself.',RECONNECT:'Strengthen connection with God and people.',REORDER:'Create room by reducing what is crowding life.',RENEW:'Gently strengthen an area that has become thin.',ABIDE:'Receive and remain in what is already giving life.'};const d=data[r.b];$('bearingTitle').textContent=r.b;$('bearingMeaning').textContent=meanings[r.b];$('bearingText').textContent=d[0]+(need?' You said you especially need '+need.toLowerCase()+'; keep that desire in view as you try this.':'');$('responses').innerHTML=d.slice(1).map(x=>'<div class="response"><strong>'+x[0]+'</strong>'+x[1]+'</div>').join('')}
window.toggleMap=()=>{$('details').classList.toggle('hide')};window.goFurther=()=>{const x=$('further');x.classList.toggle('hide');x.innerHTML='<div class="ey">Go further</div><h2>Stay with the bearing before adding more.</h2><p>If this still feels true after a week, you could explore a fuller spiritual practice or a four-week rhythm. The next version of LIFEMAP will match those practices to your season rather than prescribe a generic list.</p>'}})();
