const { test, expect } = require('@playwright/test');

function watchErrors(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});return errors}
async function startAssessment(page,mode){await page.goto('/');const label=mode==='deep'?'Begin Deeper Discernment':'Begin Formation Assessment';await page.getByRole('link',{name:label}).click();await expect(page).toHaveURL(new RegExp(`scale\\.html\\?mode=${mode}`));await page.getByRole('link',{name:label}).click();await expect(page).toHaveURL(new RegExp(`pilot-v4\\.html\\?mode=${mode}`))}
async function answerUntilPreProfile(page,max=112){let answered=0;while(await page.locator('#pre').isHidden()){answered++;expect(answered).toBeLessThanOrEqual(max);await expect(page.locator('#count')).toHaveText(`Question ${answered}`);await page.getByLabel('Somewhat true',{exact:true}).check();await page.getByRole('button',{name:'Next',exact:true}).click()}return answered}

for(const mode of ['quick','deep'])test(`${mode} V4.1 assessment completes through fruit and journey`,async({page})=>{const errors=watchErrors(page);await startAssessment(page,mode);const answered=await answerUntilPreProfile(page);if(mode==='quick')expect(answered).toBe(56);else{expect(answered).toBeGreaterThanOrEqual(84);expect(answered).toBeLessThanOrEqual(112)}await page.getByLabel('In personal prayer or quiet time with God',{exact:true}).check();await page.getByLabel('Busyness, hurry or an overloaded schedule',{exact:true}).check();await page.getByLabel('My current season significantly limits how much control I have over my time.',{exact:true}).check();await page.getByPlaceholder('I sense God may be inviting me to…').fill('Receive a less hurried rhythm in ordinary life.');await page.getByRole('button',{name:'See my Formation Profile'}).click();await expect(page.locator('#prof')).toBeVisible();await expect(page.locator('#domains .domain')).toHaveCount(14);await expect(page.locator('#areas .area')).toHaveCount(3);await expect(page.locator('#fruit')).not.toBeEmpty();await expect(page.locator('#plan .week')).toHaveCount(4);await expect(page.getByRole('button',{name:'Start my four-week journey'})).toBeVisible();const contract=await page.evaluate(()=>({version:window.FormationCurrentResult?.version,fruit:window.FormationCurrentResult?.fruit?.dimensions?.length,itemMap:window.FormationCurrentResult?.diagnostics?.itemMap,adaptive:window.FormationCurrentResult?.diagnostics?.adaptive||false}));expect(contract.version).toBe('4.1');expect(contract.fruit).toBe(6);expect(contract.itemMap).toBe('4.1-facet-map');if(mode==='deep')expect(contract.adaptive).toBe(true);await page.getByRole('button',{name:'Start my four-week journey'}).click();await expect(page.locator('#journeyStatus')).toContainText('Journey saved');expect(await page.evaluate(()=>!!localStorage.getItem('formation.v4.journey'))).toBe(true);expect(errors).toEqual([])});

test('question flow keeps Formation visible and description only on question one',async({page})=>{const errors=watchErrors(page);await startAssessment(page,'quick');await expect(page.locator('#assess .hero')).toBeVisible();await page.getByLabel('Mostly true',{exact:true}).check();await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.locator('#count')).toHaveText('Question 2');await expect(page.locator('#dn')).toHaveText('Prayer');await expect(page.locator('.brand')).toHaveText('FORMATION');await expect(page.locator('#assess .hero')).toBeHidden();expect(errors).toEqual([])});

test('sample route uses the canonical V4.1 renderer',async({page})=>{const errors=watchErrors(page);await page.goto('/sample.html');await expect(page).toHaveURL(/pilot-v4\.html\?mode=quick&sample=1/);await expect(page.locator('#prof')).toBeVisible();await expect(page.locator('#domains .domain')).toHaveCount(14);await expect(page.locator('#fruit')).not.toBeEmpty();await expect(page.locator('#plan .week')).toHaveCount(4);expect(errors).toEqual([])});

test('saved four-week journey opens reflection and supports reassessment route',async({page})=>{await page.goto('/pilot-v4.html?mode=quick&sample=1');await expect(page.locator('#prof')).toBeVisible();await page.getByRole('button',{name:'Start my four-week journey'}).click();await page.goto('/reflect.html');await expect(page.getByRole('heading',{name:'What did you notice?'})).toBeVisible();await expect(page.getByText('What did you notice about God?')).toBeVisible();await page.locator('[data-r="0"]').fill('I noticed more trust and less pressure.');await page.getByRole('button',{name:'Save reflection'}).click();await expect(page.locator('#status')).toHaveText('Reflection saved on this device.');const href=await page.getByRole('link',{name:'Reassess now'}).getAttribute('href');expect(href).toMatch(/scale\.html\?mode=quick&reassess=1/)});

test('all four development routes remain available',async({page})=>{await page.goto('/development.html');for(const name of ['Open full experience','Open algorithm harness','Open post-assessment sample','Open stress tests'])await expect(page.getByRole('link',{name})).toBeVisible()});
