const { test, expect } = require('@playwright/test');

function watchErrors(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});return errors}
async function startAssessment(page,mode){await page.goto('/');const label=mode==='deep'?'Begin Deeper Discernment':'Begin Formation Assessment';await page.getByRole('link',{name:label}).click();await expect(page).toHaveURL(new RegExp(`scale\\.html\\?mode=${mode}`));await page.getByRole('link',{name:label}).click();await expect(page).toHaveURL(new RegExp(`pilot-v4\\.html\\?mode=${mode}`))}
async function answerUntilPreProfile(page,max=112){let answered=0;while(await page.locator('#pre').isHidden()){answered++;expect(answered).toBeLessThanOrEqual(max);if(answered===1||answered%14===0)console.log(`[journey] answered ${answered}`);await expect(page.locator('#count')).toHaveText(`Question ${answered}`);await page.getByLabel('Somewhat true',{exact:true}).check();await page.getByRole('button',{name:'Next',exact:true}).click()}return answered}

test.describe('critical participant journey',()=>{
  test('quick assessment completes to profile and saves four-week journey',async({page})=>{test.setTimeout(90_000);const errors=watchErrors(page);console.log('[journey] opening quick assessment');await startAssessment(page,'quick');const answered=await answerUntilPreProfile(page,60);expect(answered).toBe(56);console.log('[journey] completing discernment');await page.getByLabel('In personal prayer or quiet time with God',{exact:true}).check();await page.getByLabel('Busyness, hurry or an overloaded schedule',{exact:true}).check();await page.getByLabel('My current season significantly limits how much control I have over my time.',{exact:true}).check();await page.getByPlaceholder('I sense God may be inviting me to…').fill('Receive a less hurried rhythm in ordinary life.');await page.getByRole('button',{name:'See my Formation Profile'}).click();console.log('[journey] checking profile contract');await expect(page.locator('#prof')).toBeVisible();await expect(page.locator('#domains .domain')).toHaveCount(14);await expect(page.locator('#areas .area')).toHaveCount(3);await expect(page.locator('#fruit .fruitcard')).toHaveCount(2);await expect(page.locator('#plan .week')).toHaveCount(4);const contract=await page.evaluate(()=>({version:window.FormationCurrentResult?.version,fruit:window.FormationCurrentResult?.fruit?.dimensions?.length,itemMap:window.FormationCurrentResult?.diagnostics?.itemMap}));expect(contract).toEqual({version:'4.1',fruit:6,itemMap:'4.1-facet-map'});await page.getByRole('button',{name:'Start my four-week journey'}).click();await expect(page.locator('#journeyStatus')).toContainText('Journey saved');expect(await page.evaluate(()=>!!localStorage.getItem('formation.v4.journey'))).toBe(true);expect(errors).toEqual([]);console.log('[journey] quick journey passed')});
});

test.describe('cross-browser smoke',()=>{
  test('quick and deep assessment shells advance cleanly',async({page})=>{for(const mode of ['quick','deep']){const errors=watchErrors(page);console.log(`[smoke] ${mode} start`);await startAssessment(page,mode);await expect(page.locator('#count')).toHaveText('Question 1');await expect(page.locator('#dn')).toHaveText('Prayer');await page.getByLabel('Mostly true',{exact:true}).check();await page.getByRole('button',{name:'Next',exact:true}).click();await expect(page.locator('#count')).toHaveText('Question 2');await expect(page.locator('.brand')).toHaveText('FORMATION');const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);expect(overflow).toBeLessThanOrEqual(1);expect(errors).toEqual([]);console.log(`[smoke] ${mode} passed`)}});

  test('sample profile renders canonical V4.1 output',async({page})=>{const errors=watchErrors(page);console.log('[smoke] sample start');await page.goto('/sample.html');await expect(page).toHaveURL(/sample-v42\.html/);await page.getByRole('button',{name:'See sample Formation Profile'}).click();await expect(page.locator('#domains .domain')).toHaveCount(14);await expect(page.locator('#areas .area')).toHaveCount(3);await expect(page.locator('#fruit .fruitcard')).toHaveCount(2);await expect(page.locator('#plan .week')).toHaveCount(4);expect(errors).toEqual([]);console.log('[smoke] sample passed')});

  test('saved journey opens reflection and reassessment route',async({page})=>{console.log('[smoke] reflection start');await page.goto('/');await page.evaluate(()=>localStorage.setItem('formation.v4.journey',JSON.stringify({version:'4.1',status:'practising',startedAt:new Date().toISOString(),returnAt:new Date(Date.now()+28*86400000).toISOString(),baseline:{mode:'quick',anchor:'Community',attention:'Sabbath',invitation:'Receive rest as grace.',plan:{headline:'Protect a Sabbath experiment.',fruitFocus:['Peace / Trust']},fruit:{themes:['Peace / Trust']}},reflection:null,reassessment:null})));await page.goto('/reflect.html');await expect(page.getByRole('heading',{name:'What did you notice?'})).toBeVisible();await page.locator('[data-r="0"]').fill('I noticed more trust and less pressure.');await page.getByRole('button',{name:'Save reflection'}).click();await expect(page.locator('#status')).toHaveText('Reflection saved on this device.');expect(await page.getByRole('link',{name:'Reassess now'}).getAttribute('href')).toMatch(/scale\.html\?mode=quick&reassess=1/);console.log('[smoke] reflection passed')});

  test('four development routes remain available',async({page})=>{console.log('[smoke] development routes start');await page.goto('/development.html');for(const name of ['Open full experience','Open algorithm harness','Open post-assessment sample','Open stress tests'])await expect(page.getByRole('link',{name})).toBeVisible();console.log('[smoke] development routes passed')});
});
